language: python
python:
    - "3.5"
    - "3.4"
    - "2.7"
sudo: false
matrix:
    fast_finish: true
    allow_failures:
      - env: TOX_ENV=py27-djangomaster
      - env: TOX_ENV=py34-djangomaster
      - env: TOX_ENV=py35-djangomaster
install:
    - pip install tox-travis
script:
    - tox
